# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Gilmar Estafa"
description: > # this means to ignore newlines until "email:"
   Resumen de mi desastrosa experiencia con Gilmar y sus estafas

email: me@syrusakbary.com
#blog logo
logo: "/assets/images/logo.png"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Syrus Akbary'
author: 'Syrus Akbary'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://gilmarestafa.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@syrusakbary'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/syrusakbary
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  # - icon:	github
  #   url:	https://github.com/syrusakbary
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
